raftGroups:
  - shardID: 1
    members:
      - id: 1
        address: "localhost:63001" # ip:port
      - id: 2
        address: "localhost:63002"
      - id: 3
        address: "127.0.0.1:63003"
  - shardID: 2
    members:
      - id: 4
        address: "localhost:64001"
      - id: 5
        address: "localhost:64002"
      - id: 6
        address: "localhost:64003"
    # - id: 7
    #   host: "remote-host"
    #   user: "root"
    #   password: "root"
    #   sshKeyPath: "/root/.ssh/id_rsa"