raftGroups:
  - shardID: 1
    members:
      - id: 1
        address: "127.0.0.1"
        name: "node-1"
      - id: 2
        address: "127.0.0.1"
        name: "node-2"
      - id: 3
        address: "127.0.0.1"
        name: "node-3"
  - shardID: 2
    members:
      - id: 4
        address: "127.0.0.1"
      - id: 5
        address: "127.0.0.1"
      - id: 6
        address: "127.0.0.1"
        # raftAddress: "127.0.0.1:63006"
        # grpcAddress: "127.0.0.1:51006"
        # httpAddress: "127.0.0.1:52006"
    # - id: 7
    #   host: "remote-host"
    #   user: "root"
    #   password: "root"
    #   sshKeyPath: "/root/.ssh/id_rsa"