raftGroups:
  - shardID: 1
    members:
      - id: 1
        raftAddress: "localhost:63001" # ip:port
        address: "localhost:51001"
      - id: 2
        raftAddress: "localhost:63002"
        address: "localhost:51002"
      - id: 3
        raftAddress: "127.0.0.1:63003"
        address: "127.0.0.1:51003"
  - shardID: 2
    members:
      - id: 4
        raftAddress: "localhost:64001"
        address: "localhost:51004"
      - id: 5
        raftAddress: "localhost:64002"
        address: "localhost:51005"
      - id: 6
        raftAddress: "localhost:64003"
        address: "localhost:51006"
    # - id: 7
    #   host: "remote-host"
    #   user: "root"
    #   password: "root"
    #   sshKeyPath: "/root/.ssh/id_rsa"