version: '3.9'

services:
  main:
    image: adaptodb-main
    container_name: adaptodb_main
    ports:
      - "60080:60080" # HTTP
      - "60081:60081" # gRPC
      - "60082:60082" # controller
    volumes:
      - ./config.yaml:/app/config.yaml
    environment:
      - NODE_ENV=production

  node1:
    image: adaptodb-node
    container_name: adaptodb_node_1
    ports:
      - "63001:63001" # Raft
      - "51001:51001" # gRPC
      - "52001:52001" # HTTP
    environment:
      - NODE_ID=1
      - GROUP_ID=1
      - RAFT_ADDRESS=localhost:63001
      - DATA_DIR=/data/node1
      - WAL_DIR=/wal/node1
      - MEMBERS=1=localhost:63001,2=localhost:63002,3=127.0.0.1:63003
      - KEYRANGE=0-100
      - CTRL_ADDRESS=localhost:60082
    volumes:
      - ./data/node1:/data
      - ./wal/node1:/wal

  node2:
    image: adaptodb-node
    container_name: adaptodb_node_2
    ports:
      - "63002:63002" # Raft
      - "51002:51002" # gRPC
      - "52002:52002" # HTTP
    environment:
      - NODE_ID=2
      - GROUP_ID=1
      - RAFT_ADDRESS=localhost:63002
      - DATA_DIR=/data/node2
      - WAL_DIR=/wal/node2
      - MEMBERS=1=localhost:63001,2=localhost:63002,3=127.0.0.1:63003
      - KEYRANGE=0-100
      - CTRL_ADDRESS=localhost:60082
    volumes:
      - ./data/node2:/data
      - ./wal/node2:/wal

  node3:
    image: adaptodb-node
    container_name: adaptodb_node_3
    ports:
      - "63003:63003" # Raft
      - "51003:51003" # gRPC
      - "52003:52003" # HTTP
    environment:
      - NODE_ID=3
      - GROUP_ID=1
      - RAFT_ADDRESS=127.0.0.1:63003
      - DATA_DIR=/data/node3
      - WAL_DIR=/wal/node3
      - MEMBERS=1=localhost:63001,2=localhost:63002,3=127.0.0.1:63003
      - KEYRANGE=0-100
      - CTRL_ADDRESS=localhost:60082
    volumes:
      - ./data/node3:/data
      - ./wal/node3:/wal

  node4:
    image: adaptodb-node
    container_name: adaptodb_node_4
    ports:
      - "64001:64001" # Raft
      - "51004:51004" # gRPC
      - "52004:52004" # HTTP
    environment:
      - NODE_ID=4
      - GROUP_ID=2
      - RAFT_ADDRESS=localhost:64001
      - DATA_DIR=/data/node4
      - WAL_DIR=/wal/node4
      - MEMBERS=4=localhost:64001,5=localhost:64002,6=localhost:64003
      - KEYRANGE=101-200
      - CTRL_ADDRESS=localhost:60082
    volumes:
      - ./data/node4:/data
      - ./wal/node4:/wal

  node5:
    image: adaptodb-node
    container_name: adaptodb_node_5
    ports:
      - "64002:64002" # Raft
      - "51005:51005" # gRPC
      - "52005:52005" # HTTP
    environment:
      - NODE_ID=5
      - GROUP_ID=2
      - RAFT_ADDRESS=localhost:64002
      - DATA_DIR=/data/node5
      - WAL_DIR=/wal/node5
      - MEMBERS=4=localhost:64001,5=localhost:64002,6=localhost:64003
      - KEYRANGE=101-200
      - CTRL_ADDRESS=localhost:60082
    volumes:
      - ./data/node5:/data
      - ./wal/node5:/wal

  node6:
    image: adaptodb-node
    container_name: adaptodb_node_6
    ports:
      - "64003:64003" # Raft
      - "51006:51006" # gRPC
      - "52006:52006" # HTTP
    environment:
      - NODE_ID=6
      - GROUP_ID=2
      - RAFT_ADDRESS=localhost:64003
      - DATA_DIR=/data/node6
      - WAL_DIR=/wal/node6
      - MEMBERS=4=localhost:64001,5=localhost:64002,6=localhost:64003
      - KEYRANGE=101-200
      - CTRL_ADDRESS=localhost:60082
    volumes:
      - ./data/node6:/data
      - ./wal/node6:/wal

